name: Test Workflow

on:
 push:
  branches: [main, feature]
 pull_request:
  branches: [feature]

jobs: 
    testing: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4

            - uses: hashicorp/setup-terraform@v3

            - name: terraform init krne wala hu
              run: terraform init
       

